development:
  adapter: postgresql
  database: theword
  username:
  host: localhost

test:
  adapter: postgresql
  database: theword
  username:
  host: localhost

production:
  adapter: postgresql
  database: theword
  username:
